services:
  pg:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
      POSTGRES_DB: event_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U event"]
      interval: 5s
      timeout: 3s
      retries: 10